<?xml version="1.0" encoding="UTF-8"?>
<!--
  Purpose:
    XSLT stylesheet to convert product configuration (version 6) to
    new portal configuration (version 7)

  Input:
    - product configuration XML file (version 6)
    - Stitchfile

  Output:
    - portal configuration XML file (version 7)

  Parameters:
    - use.xincludes: Whether to use xi:include for chunking output (default: true)
    - outputdir: The directory to write output files to (default: 'output/')
    - outputfile: The main output filename (default: 'portal.xml')
    - schemaversion: The schemaversion attribute to set in the output XML (default: '7.0')

  Author:
    Tom Schraitle

  Copyright (C) 2026 SUSE Linux GmbH
-->
<!DOCTYPE xsl:stylesheet [
  <!ENTITY uppercase "'ABCDEFGHIJKLMNOPQRSTUVWXYZ'">
  <!ENTITY lowercase "'abcdefghijklmnopqrstuvwxyz'">
]>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xi="http://www.w3.org/2001/XInclude"
  xmlns:exsl="http://exslt.org/common"
  exclude-result-prefixes="exsl"
  extension-element-prefixes="exsl">

  <xsl:output encoding="UTF-8" indent="yes" method="xml"/>
  <xsl:preserve-space elements="*"/>
  <xsl:strip-space elements="product"/>

<!-- ======== Parameters -->
  <xsl:param name="use.xincludes" select="true()" />

  <!-- Set the output directory -->
  <xsl:param name="outputdir" select="'output/'" />

  <!-- Set the main output filename -->
  <xsl:param name="outputfile" select="'portal.xml'" />

  <!-- Set the RNC schema file -->
  <xsl:param name="schemafile"></xsl:param>

  <!-- Set the schemaversion attribute in the output XML -->
  <xsl:param name="schemaversion">7.0</xsl:param>

  <!-- ID separator for autogenerated IDs -->
  <xsl:param name="id.sep">.</xsl:param>


<!-- ======== Keys -->
  <!-- Define a key to group <language> elements by their @lang attribute -->
  <xsl:key name="langKey" match="category/language[not(ancestor-or-self::product)]" use="@lang" />


<!-- ======== Variables -->
  <xsl:variable name="_transformation-map">
    <!--
      Attributes:
      * id (ID): the product ID
      * series (str): the series that this product belongs
      * family (str): the product family that this product belongs
      * rank (int): The product rank that influences the tiles on the portal homepage
      * externals (bool): Convert external links into <deliverable> and <prebuilt> elements
      * idabbrev (str): The product ID abbreviation used in <deliverable id="...">
    -->
    <config>
      <product id="appliance" series="pas" family="linux" rank="04150" idabbrev="app"/>
      <product id="cloudnative" series="pas" family="cn" rank="00030" idabbrev="cn" />
      <product id="container" series="pas" family="linux" rank="04130" externals="1" idabbrev="cont" />
      <product id="compliance" series="pas" family="linux" rank="" idabbrev="comp" />
      <product id="liberty" series="pas" family="linux" rank="00060" idabbrev="lib" />
      <product id="releasenotes" series="rn" family="linux" idabbrev="rn"/>
      <product id="sbp" series="sbp" family="linux" />
      <product id="ses" series="pas" family="linux" rank="04160" />
      <product id="sled" series="pas" family="linux" rank="04100" />
      <product id="sle-ha" series="pas" family="linux" rank="04070" />
      <product id="sle-hpc" series="pas" family="linux" rank="04110" />
      <product id="sle-micro" series="pas" family="linux" rank="00020" />
      <product id="sle-public-cloud" series="pas" family="linux" rank="04060" idabbrev="spc" />
      <product id="sle-rt" series="pas" family="linux" rank="04080" />
      <product id="sles-sap" series="pas" family="linux" rank="00050" />
      <product id="sles" series="pas" family="linux" rank="00080" />
      <product id="sle-vmdp" series="pas" family="linux" rank="04120" />
      <product id="smart" series="pas" family="linux" />
      <product id="smt" series="pas" family="linux" rank="04330" />
      <product id="soc" series="pas" family="linux" rank="04300" />
      <product id="style" series="pas" family="linux" />
      <product id="subscription" series="pas" family="linux" rank="04140" idabbrev="sub" />
      <product id="suma" series="pas" family="linux" rank="" externals="1" />
      <product id="suma-retail" series="pas" family="linux" externals="1" />
      <product id="suma-ai" series="pas" family="suse-ai" rank="00010" />
      <product id="suma-caasp" series="pas" family="linux" rank="04310" />
      <product id="suma-cap" series="pas" family="linux" rank="04320"/>
      <product id="suma-distribution-migration-system" series="pas" family="linux" idabbrev="suma-dms" />
      <product id="suma-edge" series="pas" family="suse-edge" rank="00040" />
      <product id="trd" series="trd" family="linux" />
    </config>
  </xsl:variable>
  <xsl:variable name="config" select="exsl:node-set($_transformation-map)/*" />


<!-- ======== Helper functions -->
<!--
    Template: write.file
    Writes content to a file.
    Parameters:
      filename - The filename to write to
      content - The content to write
      method - Output method (default: xml)
      encoding - Output encoding (default: UTF-8)
      indent - Whether to indent output (default: yes)
  -->
  <xsl:template name="write.file">
    <xsl:param name="filename"/>
    <xsl:param name="content"/>
    <xsl:param name="debug" select="1" />
    <xsl:param name="method" select="'xml'"/>
    <xsl:param name="encoding" select="'UTF-8'"/>
    <xsl:param name="indent" select="'yes'"/>

    <exsl:document href="{$filename}"
                   method="{$method}"
                   encoding="{$encoding}"
                   indent="{$indent}">
      <xsl:copy-of select="$content"/>
    </exsl:document>
    <xsl:if test="boolean($debug)">
      <xsl:message>Written file: <xsl:value-of select="concat('&quot;', $filename, '&quot;')" /></xsl:message>
    </xsl:if>
  </xsl:template>

  <!--
    Template: write.chunk
    Handles the logic for writing a chunk to a file or inlining it.
    Parameters:
      filename - The relative path to the output file (from outputdir)
      hreftype - The href to use for xi:include
                 Possible values: 'filename' (default), 'relative', 'none'
      content - The content to Write
  -->
  <xsl:template name="write.chunk">
    <xsl:param name="filename"/>
    <xsl:param name="hreftype" select="'filename'"/>
    <xsl:param name="manual_href" select="''"/>
    <xsl:param name="content"/>

    <xsl:choose>
      <xsl:when test="(string($use.xincludes) = 'true' or string($use.xincludes) = '1') and $filename != ''">
        <xsl:variable name="href">
           <xsl:choose>
             <xsl:when test="string($manual_href) != ''">
               <xsl:value-of select="$manual_href"/>
             </xsl:when>
             <xsl:when test="$hreftype = 'relative'">
               <xsl:call-template name="substring-after-last">
                 <xsl:with-param name="string" select="$filename"/>
                 <xsl:with-param name="char" select="'/'"/>
               </xsl:call-template>
             </xsl:when>
             <xsl:otherwise>
               <xsl:value-of select="$filename"/>
             </xsl:otherwise>
           </xsl:choose>
        </xsl:variable>

        <xi:include href="{$href}"/>

        <xsl:call-template name="write.file">
          <xsl:with-param name="filename" select="concat($outputdir, $filename)"/>
          <xsl:with-param name="content" select="$content"/>
        </xsl:call-template>
      </xsl:when>
      <xsl:otherwise>
        <xsl:copy-of select="$content"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <xsl:template name="substring-after-last">
    <xsl:param name="string" />
    <xsl:param name="char" />
    <xsl:choose>
      <xsl:when test="contains($string, $char)">
        <xsl:call-template name="substring-after-last">
          <xsl:with-param name="string" select="substring-after($string, $char)" />
          <xsl:with-param name="char" select="$char" />
        </xsl:call-template>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="$string" />
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <xsl:template name="add-pi-for-relaxng">
    <xsl:variable name="ext" select="substring($schemafile, string-length($schemafile) - 3)" />
    <xsl:if test="$schemafile != ''">
      <xsl:variable name="type">
        <xsl:choose>
          <xsl:when test="$ext = '.rnc'">application/relax-ng-compact-syntax</xsl:when>
          <xsl:when test="$ext = '.rng'">application/xml</xsl:when>
          <xsl:otherwise>
            <xsl:message terminate="yes">
              <xsl:text>Error: Unknown schema file extension for </xsl:text>
              <xsl:value-of select="$schemafile"/>
              <xsl:text>. Only .rnc and .rng are supported.</xsl:text>
            </xsl:message>
          </xsl:otherwise>
        </xsl:choose>
      </xsl:variable>
      <xsl:processing-instruction name="xml-model">
        <xsl:value-of select="concat(' href=&quot;', $schemafile, '&quot;')"/>
        <xsl:value-of select="concat(' type=&quot;', $type, '&quot;')"/>
      </xsl:processing-instruction>
      <xsl:text>&#10;</xsl:text>
    </xsl:if>
  </xsl:template>

  <xsl:template name="generate.id">
    <xsl:param name="product.idabbrev"/>
    <xsl:param name="docset"/>
    <xsl:param name="dc"/>

    <xsl:value-of select="$product.idabbrev"/>

    <xsl:if test="string($docset)">
      <xsl:value-of select="$id.sep"/>
      <xsl:value-of select="$docset"/>
    </xsl:if>

    <xsl:if test="string($dc)">
      <xsl:value-of select="$id.sep"/>
      <xsl:value-of select="translate($dc, &uppercase;, &lowercase;)"/>
    </xsl:if>
  </xsl:template>


<!-- ======== General Templates -->
  <xsl:template match="node() | @*" name="copy">
      <xsl:copy>
        <xsl:apply-templates select="node() | @*" />
      </xsl:copy>
  </xsl:template>


  <!-- ========  Ignore Templates -->
  <xsl:template match="/docservconfig/hashes"/>

  <xsl:template match="processing-instruction('xml-model')" />


  <!-- ========  Templates -->
  <xsl:template match="/docservconfig">
    <xsl:call-template name="write.file">
      <xsl:with-param name="filename" select="concat($outputdir, $outputfile)" />
      <xsl:with-param name="content">
        <xsl:call-template name="add-pi-for-relaxng" />
        <portal schemaversion="7.0" xmlns:xi="http://www.w3.org/2001/XInclude">
          <xsl:apply-templates select="categories" />
          <productfamilies>
            <item id="linux">Linux</item>
            <item id="cn">Cloud Native</item>
            <item id="suse-edge">SUSE Edge</item>
            <item id="suse-ai">SUSE AI</item>
          </productfamilies>
          <series>
            <item id="pas">Products &amp; Solutions</item>
            <item id="sbp" >SUSE Best Practices</item>
            <item id="trd">Technical References</item>
            <item id="rn">Release Notes</item>
          </series>
          <!-- <xi:include href="categories.xml" />
          <xsl:element name="include" namespace="http://www.w3.org/2001/XInclude">
            <xsl:attribute name="href">categories.xml</xsl:attribute>
          </xsl:element>
          -->
          <xsl:apply-templates select="*[not(self::categories)]" />
        </portal>
      </xsl:with-param>
    </xsl:call-template>
  </xsl:template>

  <xsl:template match="/docservconfig/categories">
    <xsl:variable name="content">
      <xsl:apply-templates select="." mode="render"/>
    </xsl:variable>

    <xsl:call-template name="write.chunk">
      <xsl:with-param name="filename" select="'categories.xml'"/>
      <xsl:with-param name="content" select="$content"/>
    </xsl:call-template>
  </xsl:template>

  <xsl:template match="/docservconfig/categories" mode="render">
    <categories xmlns:xi="http://www.w3.org/2001/XInclude">
      <xsl:copy-of select="@*"/>
      <!-- Select only the first occurring <language> element for each unique @lang -->
      <xsl:for-each select="category/language[generate-id() = generate-id(key('langKey', @lang)[1])]">
        <xsl:variable name="currentLang" select="@lang" />

        <xsl:variable name="content">
          <!-- Create the new <category> element grouped by language -->
          <category lang="{$currentLang}">

            <!-- Retrieve all <language> elements that match the current @lang -->
            <xsl:for-each select="key('langKey', $currentLang)">
               <!-- Create an <language> for each, pulling categoryid from its parent -->
              <language id="{../@categoryid}" title="{@title}" />
            </xsl:for-each>
          </category>
        </xsl:variable>

        <xsl:call-template name="write.chunk">
           <xsl:with-param name="filename" select="concat('categories/', $currentLang, '.xml')"/>
           <xsl:with-param name="content" select="$content"/>
        </xsl:call-template>
      </xsl:for-each>
    </categories>
  </xsl:template>

  <!-- Product  -->
  <!-- don't copy these attributes -->
  <xsl:template match="product/processing-instruction()" />
  <xsl:template match="product/@schemaversion" />
  <xsl:template match="product/@site-section" />

  <xsl:template match="product/@productid">
    <xsl:variable name="id" select="." />
    <xsl:attribute name="id">
      <xsl:value-of select="$id" />
    </xsl:attribute>
  </xsl:template>

  <xsl:template match="product">
    <xsl:variable name="id" select="@productid" />
    <xsl:variable name="cnfg" select="$config/product[@id=$id]" />

    <!-- Capture the product content -->
    <xsl:variable name="content">
      <xsl:apply-templates select="." mode="render"/>
    </xsl:variable>

    <xsl:call-template name="write.chunk">
      <xsl:with-param name="filename" select="concat($id, '/', $id, '.xml')"/>
       <xsl:with-param name="content" select="$content"/>
    </xsl:call-template>
  </xsl:template>

  <xsl:template match="product" mode="render">
    <xsl:variable name="id" select="@productid" />
    <xsl:variable name="cnfg" select="$config/product[@id=$id]" />
    <product xmlns:xi="http://www.w3.org/2001/XInclude">
        <xsl:apply-templates select="@*" />
        <!-- Add new attributes based on the transformation map -->
        <xsl:attribute name="family">
          <xsl:value-of select="$cnfg/@family" />
        </xsl:attribute>
        <xsl:attribute name="series">
          <xsl:value-of select="$cnfg/@series" />
        </xsl:attribute>
        <xsl:attribute name="rank">
          <xsl:value-of select="$cnfg/@rank" />
        </xsl:attribute>

        <xsl:apply-templates select="name"/>
        <xsl:apply-templates select="sortname"/>
        <xsl:apply-templates select="acronym"/>
        <xsl:apply-templates select="maintainers"/>

        <!-- Handle desc elements -->
        <xsl:if test="desc">
          <xsl:variable name="content">
             <descriptions xmlns:xi="http://www.w3.org/2001/XInclude">
                <xsl:for-each select="desc">
                   <xsl:variable name="lang" select="@lang"/>
                   <xsl:variable name="inner_content">
                      <xsl:apply-templates select="." />
                   </xsl:variable>

                   <xsl:call-template name="write.chunk">
                      <xsl:with-param name="filename" select="concat($id, '/desc/', $lang, '.xml')"/>
                      <xsl:with-param name="hreftype" select="'relative'"/>
                      <xsl:with-param name="content" select="$inner_content"/>
                   </xsl:call-template>
                </xsl:for-each>
             </descriptions>
          </xsl:variable>

          <xsl:call-template name="write.chunk">
             <xsl:with-param name="filename" select="concat($id, '/desc/desc.xml')"/>
             <xsl:with-param name="manual_href" select="'desc/desc.xml'"/>
             <xsl:with-param name="content" select="$content"/>
          </xsl:call-template>
        </xsl:if>

        <xsl:apply-templates select="node()[not(self::desc) and not(self::name) and not(self::sortname) and not(self::acronym) and not(self::maintainers)]" />
    </product>
  </xsl:template>

  <!-- We ignore the product/category as this was moved to portal/categories -->
  <xsl:template match="product/category" />

  <xsl:template match="product/desc/@default" />

  <xsl:template match="product/@productid">
    <xsl:attribute name="id">
      <xsl:value-of select="."/>
    </xsl:attribute>
  </xsl:template>

  <!-- Docset -->
  <xsl:template match="docset/@schemaversion" />
  <xsl:template match="docset/processing-instruction()" />

  <xsl:template match="docset">
     <xsl:variable name="id" select="ancestor::product/@productid"/>
     <xsl:variable name="ver" select="@setid"/>
     <xsl:variable name="subpath" select="concat($id, '/', $ver, '.xml')"/>

     <xsl:variable name="content">
        <docset xmlns:xi="http://www.w3.org/2001/XInclude">
           <xsl:apply-templates select="@*|node()" />
        </docset>
     </xsl:variable>

     <xsl:call-template name="write.chunk">
        <xsl:with-param name="filename" select="$subpath"/>
        <xsl:with-param name="hreftype" select="'relative'"/>
        <xsl:with-param name="content" select="$content"/>
     </xsl:call-template>
  </xsl:template>

  <xsl:template match="docset/@setid">
    <xsl:attribute name="id">
      <xsl:value-of select="concat(ancestor::product/@productid, $id.sep, .)" />
    </xsl:attribute>
    <xsl:attribute name="path">
      <xsl:value-of select="."/>
    </xsl:attribute>
  </xsl:template>

  <xsl:template match="docset/overridedesc">
    <descriptions>
      <xsl:copy-of select="@*"/>
      <xsl:apply-templates/>
    </descriptions>
  </xsl:template>

  <xsl:template match="docset/builddocs">
    <resources>
      <xsl:apply-templates/>
    </resources>
  </xsl:template>

  <xsl:template match="docset/builddocs/language">
    <xsl:variable name="pid" select="ancestor::product/@productid"/>
    <xsl:variable name="do_externals" select="$config[@id=$pid]/@externals"/>
    <xsl:variable name="current_lang" select="@lang"/>

    <locale>
      <xsl:copy-of select="@lang" /><!-- no default attribute -->
      <xsl:apply-templates />

      <xsl:if test="$do_externals">
         <xsl:apply-templates select="../../external/link[language[@lang = $current_lang]]" mode="convert-to-prebuilt">
            <xsl:with-param name="lang" select="$current_lang"/>
         </xsl:apply-templates>
      </xsl:if>
    </locale>
  </xsl:template>

  <xsl:template match="link/language/@default" />

  <!-- deliverable -->
  <xsl:template match="language[@lang='en-us']/deliverable">
    <xsl:variable name="pid" select="ancestor::product/@productid"/>
    <xsl:variable name="abbrev" select="$config/product[@id=$pid]/@idabbrev"/>
    <xsl:variable name="product.idabbrev" select="$abbrev | $pid[not($abbrev)]"/>
    <xsl:variable name="id">
      <xsl:call-template name="generate.id">
        <xsl:with-param name="product.idabbrev" select="$product.idabbrev"/>
        <xsl:with-param name="docset" select="ancestor::docset/@setid"/>
        <xsl:with-param name="dc" select="dc"/>
      </xsl:call-template>
    </xsl:variable>

    <deliverable id="{$id}" type="dc">
      <xsl:copy-of select="@*"/>
      <xsl:apply-templates />
    </deliverable>
  </xsl:template>

  <xsl:template match="language[@lang!='en-us']/deliverable">
    <xsl:variable name="pid" select="ancestor::product/@productid"/>
    <xsl:variable name="abbrev" select="$config/product[@id=$pid]/@idabbrev"/>
    <xsl:variable name="product.idabbrev" select="$abbrev | $pid[not($abbrev)]"/>
    <xsl:variable name="id">
      <xsl:call-template name="generate.id">
        <xsl:with-param name="product.idabbrev" select="$product.idabbrev"/>
        <xsl:with-param name="docset" select="ancestor::docset/@setid"/>
        <xsl:with-param name="dc" select="dc"/>
      </xsl:call-template>
    </xsl:variable>

    <ref linkend="{$id}" />
  </xsl:template>

  <!-- ref  -->
  <xsl:template match="ref">
    <xsl:variable name="pid" select="@product"/>
    <xsl:variable name="cnfg" select="$config/product[@id=$pid]"/>
    <xsl:variable name="abbrev" select="$cnfg/@idabbrev"/>
    <xsl:variable name="product.idabbrev" select="$abbrev | $pid[not($abbrev)]"/>
    <xsl:variable name="ref" >
      <xsl:choose>
        <xsl:when test="not(@docset) and not(@dc)">
          <xsl:call-template name="generate.id">
            <xsl:with-param name="product.idabbrev" select="$product.idabbrev"/>
          </xsl:call-template>
        </xsl:when>
        <xsl:when test="@product and @docset and not(@dc)">
          <xsl:call-template name="generate.id">
            <xsl:with-param name="product.idabbrev" select="$product.idabbrev"/>
            <xsl:with-param name="docset" select="@docset"/>
          </xsl:call-template>
        </xsl:when>
        <xsl:when test="@product and @docset and @dc">
          <xsl:call-template name="generate.id">
            <xsl:with-param name="product.idabbrev" select="$product.idabbrev"/>
            <xsl:with-param name="docset" select="@docset"/>
            <xsl:with-param name="dc" select="@dc"/>
          </xsl:call-template>
        </xsl:when>
        <xsl:when test="@deliverable">
          <xsl:value-of select="concat(@product, $id.sep, @docset, $id.sep, @deliverable)"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:message>WARN: Couldn't create a linkend for &lt;ref <xsl:for-each select="@*">
              <xsl:value-of select="concat(local-name(.), '=&quot;', ., '&quot; ')"/>
          </xsl:for-each>
          <xsl:text>/&gt;</xsl:text>
          </xsl:message>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>
    <!--<xsl:message>ref: <xsl:value-of select="count($cnfg)"/>
      product=<xsl:value-of select="concat(@product, '::', $pid)"/>
      idabbrev=<xsl:value-of select="$abbrev"/>
    </xsl:message>-->
    <ref linkend="{$ref}">
      <xsl:copy-of select="@category|@titleformat"/>
    </ref>
  </xsl:template>


  <!-- desc -->
  <xsl:template match="desc/@default" />

</xsl:stylesheet>
