# https://towncrier.readthedocs.io/en/stable/configuration.html

[tool.towncrier]
package = "docbuild"
package_dir = "src"
filename = "CHANGELOG.rst"
directory = "changelog.d/"
title_format = "Version {version}"
# template = "changelog.d/_template.rst"
# issue_format = "`#{issue} <https://github.com/python-attrs/attrs/issues/{issue}>`_"
issue_format = ":gh:`{issue}`"


# HINT:
# If you change one of the types, make sure you document them in the
# file docs/source/developer/add-newsfragments.txt
[tool.towncrier.fragment.breaking]
name = "Breaking Changes"

[tool.towncrier.fragment.bugfix]
name = "Bug Fixes"

[tool.towncrier.fragment.deprecation]
name = "Deprecations"

[tool.towncrier.fragment.doc]
name = "Improved Documentation"

[tool.towncrier.fragment.feature]
name = "Features"

[tool.towncrier.fragment.removal]
name = "Removed Features"

[tool.towncrier.fragment.infra]
name = "Infrastructure"

[tool.towncrier.fragment.refactor]
name = "Code Refactoring"
