name: Bug Report
description: Report a reproducible bug or unexpected behavior.
labels: [bug]
assignees: [tomschr]
type: bug

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below so we can help.

  - type: input
    id: project_version
    attributes:
      label: Project Version
      description: What version of this project are you using?
      placeholder: e.g., 1.2.3
    validations:
      required: true

  - type: dropdown
    id: python_version
    attributes:
      label: Python Version
      description: Which version of Python is the problem with?
      multiple: true
      options:
        - "3.11"
        - "3.12"
        - "3.13"
        - "3.14"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      multiple: true
      options:
        - Linux
        - Windows
        - macOS
        - Other (describe below)
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the issue? Please provide a minimal example.
      placeholder: |
        1. Run this command...
        2. See this output...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: |
        I expected the command to return this output...
        Or, I expected the application to behave like this...
    validations:
      required: false

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: |
        Instead, I got this output...
        Or, the application crashed with this error...
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Additional Information
      description: |
        Any other relevant information? (e.g., logs, environment variables, installed packages)
      placeholder: |
        - Logs:
        - Output from the command:
        - Error messages:
        - Environment variables:
        - Installed packages:
    validations:
      required: false
