name: Documentation Update
description: Propose improvements or corrections to the documentation.
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve the documentation! Please describe what needs updating.

  - type: input
    id: affected_section
    attributes:
      label: Affected Documentation Section
      description: Which part of the docs needs updating?
      placeholder: e.g., README, Installation section, Usage instructions
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Change
      description: What should be changed or improved?
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Context
      description: Any other information, screenshots, or references?
    validations:
      required: false