name: CI/Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  test-ubuntu:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/documentation/containers/15.6/opensuse-daps-toolchain:latest
      # image: ghcr.io/opensuse/docbuild/daps:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          rpm -q daps \
            suse-xsl-stylesheets \
            suse-xsl-stylesheets-sbp \
            geekodoc \
            docbook-xsl-stylesheets \
            docbook-xsl-ns \
            xmlgraphics-fop \
            git \
            ditaa \
            libreoffice-draw \
            novdoc \
            ruby2.5-rubygem-asciidoctor \
            curl \
            tar \
            w3m \
            jq \
            rsvg-convert \
            openssh-clients || true

      - name: Install the latest version of uv
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
            version: "latest"
            enable-cache: true
            cache-suffix: "docbuild"

      - name: Print the installed version
        run: echo "Installed uv version is ${{ steps.setup-uv.outputs.uv-version }}"

      - name: Install dependencies
        run: uv sync --frozen --group devel

      - name: Run tests
        run: |
           uv run --frozen pytest -vv

  test-macos:
    name: macos-latest
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv and dependencies
        run: |
          pip install uv
          uv sync --frozen --group devel
          pip install pytest-cov click
          
      - name: Install external tools (macOS)
        run: |
          # Download jing tool directly and place it in the PATH.
          JING_VERSION="20181222" # Use a known stable version
          JING_URL="https://repo1.maven.org/maven2/com/thaiopensource/jing/${JING_VERSION}/jing-${JING_VERSION}.jar"
          
          # Install external tools on macOS using Homebrew
          brew install libxml2 libxslt
          
          # Add the keg-only Homebrew paths to the PATH for the current shell session
          echo "/opt/homebrew/opt/libxml2/bin" >> $GITHUB_PATH
          echo "/opt/homebrew/opt/libxslt/bin" >> $GITHUB_PATH
          
          # Set up the jing executable
          curl -sL -f $JING_URL -o jing.jar
          if [ ! -f jing.jar ]; then
            echo "Error: Failed to download jing.jar"
            exit 1
          fi
          
          echo '#!/bin/bash' > jing
          echo '/usr/bin/java -jar jing.jar "$@"' >> jing
          chmod +x jing
          
          # Use the correct, modern way to add to PATH
          echo "$(pwd)" >> $GITHUB_PATH

      - name: Run tests
        run: |
          stty cols 120
          pytest -vv
