name: CI/Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  test:
    name: python
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/documentation/containers/15.6/opensuse-daps-toolchain:latest
      # image: ghcr.io/opensuse/docbuild/daps:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          rpm -q daps \
            suse-xsl-stylesheets \
            suse-xsl-stylesheets-sbp \
            geekodoc \
            docbook-xsl-stylesheets \
            docbook-xsl-ns \
            xmlgraphics-fop \
            git \
            ditaa \
            libreoffice-draw \
            novdoc \
            ruby2.5-rubygem-asciidoctor \
            curl \
            tar \
            w3m \
            jq \
            rsvg-convert \
            openssh-clients || true

      - name: Install the latest version of uv
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
            version: "latest"
            enable-cache: true
            cache-suffix: "docbuild"

      - name: Print the installed version
        run: echo "Installed uv version is ${{ steps.setup-uv.outputs.uv-version }}"

      - name: Install dependencies
        run: uv sync --frozen --group devel

      - name: Run tests
        run: |
           uv run --frozen pytest -vv
