name: CI/Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  test-ubuntu:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/documentation/containers/15.6/opensuse-daps-toolchain:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pip
        run: |
          zypper refresh
          zypper install -y python3-pip

      - name: Install uv and dependencies
        run: |
          pip install uv
          uv sync --frozen --group devel

      - name: Run tests
        run: |
           uv run --frozen pytest -vv

  test-macos:
    name: macos-latest
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv and dependencies
        run: |
          pip install uv
          uv sync --frozen --group devel
          pip install pytest-cov # Add pytest-cov for coverage reports if needed

      - name: Install external tools (macOS)
        run: |
          # Use Homebrew on macOS to install tools, correcting "xsltproc" to "libxslt".
          brew install libxml2 libxslt
          
          # Download jing tool directly and place it in the PATH.
          JING_VERSION="20181222" # Use a known stable version
          JING_URL="https://repo1.maven.org/maven2/com/thaiopensource/jing/${JING_VERSION}/jing-${JING_VERSION}.jar"
          curl -sL $JING_URL -o jing.jar
          echo '#!/bin/bash' > jing
          echo 'java -jar jing.jar "$@"' >> jing
          chmod +x jing
          
          # Add the current directory to the PATH to find jing
          echo "::add-path::$(pwd)"

      - name: Run tests
        run: |
          pytest -vv
