name: CI/Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  test:
    name: python (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    container:
      image: registry.opensuse.org/documentation/containers/15.6/opensuse-daps-toolchain:latest
      # image: ghcr.io/opensuse/docbuild/daps:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install --cask docker
          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
          open -a Docker
          # Wait for Docker to start
          while ! docker system info > /dev/null 2>&1; do
            echo "Waiting for Docker to start..."
            sleep 5
          done

      - name: Get dependencies
        run: |
          rpm -q --qf '%-30{NAME} %{VERSION}\n' \
            curl \
            daps \
            ditaa \
            docbook-xsl-ns-stylesheets \
            docbook-xsl-stylesheets \
            geekodoc \
            git \
            jq \
            libreoffice-draw \
            novdoc \
            openssh-clients \
            rsvg-convert \
            ruby2.5 \
            suse-xsl-stylesheets \
            tar \
            w3m \
            xmlgraphics-fop || true

      - name: Install tools (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install jing libxml2-utils xsltproc

      - name: Install the latest version of uv
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
            version: "latest"
            enable-cache: true
            cache-suffix: "docbuild"

      - name: Print the installed version
        run: echo "Installed uv version is ${{ steps.setup-uv.outputs.uv-version }}"

      - name: Install dependencies
        run: uv sync --frozen --group devel

      - name: Run tests
        run: |
           uv run --frozen pytest -vv
