name: Build and Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ci/Dockerfile'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -f ci/Dockerfile -t ghcr.io/${{ github.repository }}/daps:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/daps:${{ github.sha }}

      # (Optional) Tag as latest if on main
      - name: Tag latest image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ghcr.io/${{ github.repository }}/daps:${{ github.sha }} ghcr.io/${{ github.repository }}/daps:latest
          docker push ghcr.io/${{ github.repository }}/daps:latest
